[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.136.5"

[[redirects]]
  from = "https://www.danharr.is/*"
  to = "https://danharr.is/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://danmharris.com/*"
  to = "https://danharr.is/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.danmharris.com/*"
  to = "https://danharr.is/:splat"
  status = 301
  force = true
