version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: ~/personal-website
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy to S3
          command: aws s3 sync /tmp/workspace/public s3://dan-harris-personal-website/ --delete
      - run:
          name: Invalidate cloudfront cache
          command: aws cloudfront create-invalidation --distribution-id E1HZ7YMVH9SL2L --paths "/*"
orbs:
  hugo: circleci/hugo@1.0.0
workflows:
  build-deploy:
    jobs:
      - hugo/build:
          html-proofer: true
      - deploy:
          requires:
            - hugo/build
          filters:
            branches:
              only: master
